# Copilot addition: deployment prep - Docker Compose for local development
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiktalk-api
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=${API_DEBUG:-false}
      - ACCOUNTS_DIR=/app/accounts
      - DATA_DIR=/app/data
      - CONFIG_DIR=/app/config
    volumes:
      - ./accounts:/app/accounts
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/verify/system')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./synapse-ai-learning-main
      dockerfile: Dockerfile.frontend
    container_name: tiktalk-frontend
    ports:
      - "5001:5001"
    environment:
      - VITE_API_BASE=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: tiktalk-network
